// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:c110a18e-82a3-4505-ad92-3c508cc88d1c",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_P52GHiEQH",
    "aws_user_pools_web_client_id": "79j2tb9sl2rptv6knhfhbcgg5k",
    "aws_dynamodb_all_tables_region": "ap-northeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Videos",
            "region": "ap-northeast-1"
        }
    ],
    "aws_user_files_s3_bucket": "video-upload-qejsadfqwefadfafqwef-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "apiGetAllVideos",
            "endpoint": "https://p6qirenmzj.execute-api.ap-northeast-1.amazonaws.com/Prod",
            "region": "ap-northeast-1"
        },
        {
            "name": "apiUpVote",
            "endpoint": "https://ednzpydcyc.execute-api.ap-northeast-1.amazonaws.com/Prod",
            "region": "ap-northeast-1"
        }
    ],
    "aws_content_delivery_bucket": "video-transcoded-yewnsdiqsdfq-dev",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "https://dr8yjtnfa00ar.cloudfront.net"
};


export default awsmobile;
