service: video-broadcast

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  profile: global
  region: us-east-1
  memorySize: 512
  iamRoleStatements: 
    - Effect: Allow
      Action: 
        - s3:GetObject
        - s3:PutObject
      Resource: "arn:aws:s3:::*"
    - Effect: Allow
      Action: 
        - elastictranscoder:Read*
        - elastictranscoder:List*
        - elastictranscoder:*Job
        - elastictranscoder:*Preset
        - s3:List*
        - iam:List*
        - sns:List*
      Resource: "*"


functions:
  get-user-profile:
    handler: user-profile/index.handler
    events:
      - http:
          path: user-profile
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                accessToken: false
              headers:
                authorization: false
          authorizer:
            name: custom-authorizer
            identitySource: method.request.header.Authorization
    environment:
      AUTH0_DOMAIN: harold-mb.auth0.com

  custom-authorizer:
    handler: custom-authorizer/index.handler

  transcode-video:
    handler: transcode-video-firebase-enabled/index.handler
    events:
      - s3:
          bucket: video-upload-wezvqwefqef
          event: s3:ObjectCreated:*
    environment: 
      DATABASE_URL: https://harold-mb.firebaseio.com/
      ELASTIC_TRANSCODER_PIPELINE_ID: 1526379306887-6f66we
      ELASTIC_TRANSCODER_REGION: us-east-1
      SERVICE_ACCOUNT: harold-mb-key.json

  get-upload-policy: 
    handler: create-s3-upload-policy-document/index.handler
    events: 
      - http:
          path: s3-policy-document
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                accessToken: false
              headers:
                authorization: false
          authorizer:
            name: custom-authorizer
            identitySource: method.request.header.Authorization
    environment:
      ACCESS_KEY_ID: AKIAJMJS2MELCMAHSHHA
      SECRET_ACCESS_KEY: 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
      UPLOAD_BUCKET: video-upload-wezvqwefqef
      UPLOAD_URI: https://s3.amazonaws.com

  push-transcoded-url-to-firebase: 
    handler: push-transcoded-url-to-firebase/index.handler
    events:
      - s3: 
          bucket: video-transcoded-qezsdqwerqwr
          event: s3:ObjectCreated:*
    environment: 
      DATABASE_URL: https://harold-mb.firebaseio.com/
      S3_TRANSCODED_BUCKET_URL: https://s3.amazonaws.com/harold-mb2-transcoded
      SERVICE_ACCOUNT: harold-mb-key.json    

resources:
  Resources:
    S3BucketPermissions:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: video-transcoded-qezsdqwerqwr
        PolicyDocument:
          Statement:
            - Principal: "*"
              Action:
                - s3:GetObject
              Effect: Allow
              Sid: "AddPerm"
              Resource: arn:aws:s3:::video-transcoded-qezsdqwerqwr/*